[package]
name = "xbinser"
version = "0.1.1"
edition = "2021"
description = "library for binary structure transporation"
license = "MIT"

[dependencies]
bytemuck = { version = "1.18.0", features = ["extern_crate_std", "min_const_generics"] }
