[package]
name = "xbinser-macros"
version = "0.1.0"
edition = "2021"
description = "library for binary structure transporation, macros to generate encode and decode tools"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.37"
syn = "2.0.76"
